### ISSUE TITLE
-pack support

### ISSUE THREAD

**Issue by dsheets** [ocaml-doc/doc-ock#35]
Resolutions through pack names fail.

**Comment by dsheets** [comment]
This is necessary for references into camlp4 for example (to read camlp4 syntax extension interfaces).

**Comment by dsheets** [comment]
This is the second most critical of the currently outstanding issues (after #36).

**Comment by Drup** [comment]
Also cause issues with ocamlgraph.

**Comment by dsheets** [comment]
I have some questions about packs:

1. I am currently using cmti-with-no-cmi as the pack child signal. Is this correct?
2. I am currently using cmi-and-cmt as the maybe pack parent signal. If both are present but cmti is not, I check the cmt for pack-ness and switch the source to that if pack is found and then use the cmi extraction otherwise. Is this correct? This seems overly complicated and fragile. Is there no better way?
3. When and how should I perform expansion? If I expand before resolving, `None` is returned from expansion. If I resolve and then expand, the result is a nonsensical mash of modules (e.g. there are no second level modules, the root module becomes a second level module, and its children are a combination of third level modules from different parents, all second level links are unresolved). If I resolve again (after resolve then expand), The second level modules resolve to their unpacked paths and the module mess is still there.

**Comment by lpw25** [comment]
> I am currently using cmti-with-no-cmi as the pack child signal. Is this correct?

There is no reliable way to detect what is and what isn't a pack child. Any module that you find may be part of a pack. Modules may also be both part of a pack and available on their own. The cmti-with-no-cmi case (and the cmt-with-no-cmi case) is an important one for packs because it makes a module available to the documentation system without also making it available as a stand-alone module -- which is normally the right thing for the child of a pack.

So we need to be able to support packs without knowing in advance which things are their children. Luckily this is not very hard, as long as all possible children (i.e. all modules) are available to the "expander" via its `'a -> 'a Unit.t` argument then `expand_unit` can merge the contents of the pack to create a `'a Signature.t`.

The special treatment required for cmti-with-no-cmi (and cmt-with-no-cmi) is that they should be available to the expander, but they should not be turned into their own stand-alone module files. The `hidden` field of `Unit.t` is designed to help with this process: you should mark such files as `hidden` and then don't produce output for `hidden` units. (At some point all the types will have a `hidden` field for handling other forms of hiding).

> I am currently using cmi-and-cmt as the maybe pack parent signal. If both are present but cmti is not, I check the cmt for pack-ness and switch the source to that if pack is found and then use the cmi extraction otherwise. Is this correct? This seems overly complicated and fragile. Is there no better way?

You don't really need to detect whether a unit is a pack or not, the resolver will happily resolve pack units, and the expander should happily expand both packs and non-packs. Regardless of whether something is a pack or not, if there is a cmt file and its `interface` field is `true` (which means that there was no explicit mli file for this module and so the cmt file is an accurate representation of the interface of the module) then it is a better source of documentation than the cmit file.

I believe that the correct file detection logic is roughly:

```
let hidden = if cmi exists then false else true in
let unit =
  if cmti exists then read cmti
  else if cmt exists then
    let cmt = read cmt in
      if cmt.interface then cmt
      else if cmi exists then read cmi
      else cmt
         (* This last case is dubious -- we know that the cmt file is not the interface
              but we have no other file for that module so we use it anyway -- it would
              also be reasonable to just ignore the module at this point. *)
in
  { unit with hidden }
```

> When and how should I perform expansion? If I expand before resolving, None is returned from expansion. If I resolve and then expand, the result is a nonsensical mash of modules (e.g. there are no second level modules, the root module becomes a second level module, and its children are a combination of third level modules from different parents, all second level links are unresolved). If I resolve again (after resolve then expand), The second level modules resolve to their unpacked paths and the module mess is still there.

You should use it after resolving (probably as part of generating the html), and you should not need to run resolving again afterwards. The problems you describe are a collection of stupid bugs which I will fix shortly.

I have started generating some docs locally now. I hacked together basic pack support in codoc (I haven't sent a pull request because it really is a hack and not worth including upstream) and I'm now going to start working through the bugs in the output.

**Comment by lpw25** [comment]
I've pushed fixes for some of the bugs. There is still something going wrong with the substitution, which means references between the packed modules are not correct.
